apiVersion: v1
kind: PersistentVolume
metadata:
  name: chhoto-pv
  labels:
    app: chhoto-url
spec:
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data/chhoto-data
