name: Test and Docker Release
on:
  push:
    tags:
      - '*'
  workflow_dispatch:
env:
  CARGO_TERM_COLOR: always
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    name: Release - ${{ matrix.platform.os-name }}
    strategy:
      matrix:
        include:
          - os-name: Linux-x86_64
            target: x86_64-unknown-linux-musl

          - os-name: Linux-aarch64
            target: aarch64-unknown-linux-musl

          - os-name: Linux-armv7
            target: armv7-unknown-linux-musleabihf

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build binary
        uses: houseabsolute/actions-rust-cross@v1
        with:
          command: both
          target: ${{ matrix.include.target }}
          args: "--locked --release --manifest-path=actix/Cargo.toml"
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.include.target }}
          path: ./actix/target/${{ matrix.include.target }}/release/${{ github.repository }}
          retention-days: 1
          if-no-files-found: error

  merge:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
      - name: Display structure of downloaded files
        run: ls -R
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ env.IMAGE_NAME }}
          tags: |
            type=semver,pattern={{major}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{version}}
            type=raw,value=dev,enable=${{ github.ref == format('refs/heads/{0}', 'ci-testing') }}

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
      
      - name: Generate artifact attestation
        uses: actions/attest-build-provenance@v2
        with:
          file: "{context}/Dockerfile.multiarch"
          subject-name: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME}}
          subject-digest: ${{ steps.push.outputs.digest }}
          push-to-registry: true
          platforms: linux/amd64,linux/arm64,linux/arm/v7
