name: Rust

on:
  push:
    branches: [ "main" ]
    paths: [ "actix/**" ]
  pull_request:
    branches: [ "main" ]
    paths: [ "actix/**" ]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose
      working-directory: actix
    - name: Run tests
      run: cargo test --verbose
      working-directory: actix
