name: Tests

on:
  push:
    branches: [ "main" ]
    paths: [ "actix/**" ]
  pull_request:
    branches: [ "main" ]
    paths: [ "actix/**" ]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Cache Dependencies
      uses: actions/cache@v3
      with:
        path: |
          ./target
          ~/.cargo
        key: debug-${{ runner.os }}-${{ hashFiles('rust-toolchain.toml') }}-${{ hashFiles('Cargo.lock') }}
        restore-keys: |
            debug-${{ runner.os }}-${{ hashFiles('rust-toolchain.toml') }}-
            debug-${{ runner.os }}-
        working-directory: actix
    - name: Run tests
      run: cargo test --verbose
      working-directory: actix
